Генерация исключений в JavaScript
Ошибки выдает движок, а исключения выдает разработчик. Но что именно это означает? В JavaScript все исключения — это просто объекты. Хотя большинство исключений являются реализациями глобального класса Error, любой старый объект может быть сгенерирован. Имея это в виду, есть два способа вызвать исключение: напрямую через объект Error и через пользовательский объект.

Общие исключения
Хотя встроенный класс Error довольно хорошо определен, включая такие вещи, как имя файла, номер строки и трассировка стека и многие другие, когда дело доходит до него, самое важное, на что следует обратить внимание, — это сообщение. Первый и часто единственный параметр, передаваемый во время создания экземпляра ошибки, — это сообщение об ошибке, понятное человеку, которое часто может быть связано непосредственно с конечным пользователем. Создание общего исключения почти так же просто, как кажется. Все, что требуется, — это создать экземпляр объекта исключения — с первым параметром конструктора Error, являющимся сообщением об ошибке, — а затем… «выбросить» его.

throw new Error('Exception message');
error.code против error.message
Здесь важно отметить, что хотя сообщение об ошибке представляет собой удобочитаемые данные об ошибке, Node.js также предоставляет код ошибки , который определяет тип возникающей ошибки. Это значение полезно, так как оно позволяет программно адаптироваться к ошибкам, которые могут возникнуть, независимо от сообщения, содержащегося в ошибке.

Хотя коды ошибок обычно используются для системных ошибок, при создании пользовательских ошибок путем расширения класса ошибок (дополнительные сведения см. в разделе Пользовательские исключения ниже) можно определить пользовательский код и использовать его для более структурированных определений ошибок.

function CustomException(message) {
const error = new Error(message);

error.code = "THIS_IS_A_CUSTOM_ERROR_CODE";
return error;
}

CustomException.prototype = Object.create(Error.prototype);
Пользовательские исключения
Хотя можно выбросить любой объект, лучше всего расширить объект Error новым классом. В средах, которые его поддерживают, это позволяет включать такие функции, как автоматическая трассировка стека, в ответ на исключение, что может иметь решающее значение, когда дело доходит до диагностики проблем в дальнейшем.

function CustomException(message) {
const error = new Error(message);
return error;
}

CustomException.prototype = Object.create(Error.prototype);
Создав пользовательский объект исключения, все, что нам нужно сделать, это выдать его, как и любую другую ошибку:

throw new CustomException('Exception message');
Еще одним большим преимуществом расширения объекта Error, а не создания общей ошибки, является то, что дополнительные метаданные могут быть включены в ошибку и извлечены позже. Это может быть невероятно полезно при отладке и сообщении об ошибках, поскольку иногда простого текстового сообщения просто недостаточно. Например, вы можете включить значения локальных переменных или состояния, которые помогут вам отладить проблему.

function CustomException(message, metadata) {
const error = new Error(message);
error.metadata = metadata;
return error;
}
Помимо данных, включенных в объект Error, при использовании уведомления Rollbar для JavaScript в отчет также включаются дополнительные данные. Сюда входит контекстная информация, такая как браузер и пользователь.

// Caught errors
try {
doSomething();
} catch (e) {
Rollbar.error("Something went wrong", e);
}
Запись в консоль
В JavaScript консоль — это место, где можно найти все журналы (подробнее об этом в разделе Где регистрируются ошибки JavaScript? ). К счастью, на самом деле запись данных в консоль невероятно проста. Для этого просто вызовите метод console.log() с сообщением, которое вы хотите записать в журнал.

console.log("Top level");
Как создавать исключения во Flutter
